"""InputBackend interface.

All action emission flows through this protocol. Coordinates are always
screen-absolute pixels; lens-relative conversion happens upstream in the
action zone.

Touch-style gestures (tap, long_press, swipe) are synthesized from mouse
primitives on the DesktopBackend. Future backends may map them differently.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class InputBackend(Protocol):
    def click(self, x: int, y: int, button: str = "left") -> None: ...
    def double_click(self, x: int, y: int) -> None: ...
    def triple_click(self, x: int, y: int) -> None: ...
    def long_press(self, x: int, y: int, duration: float = 1.0) -> None: ...
    def swipe(
        self, x1: int, y1: int, x2: int, y2: int, duration: float = 0.3
    ) -> None: ...
    def mouse_move(self, x: int, y: int) -> None: ...
    def mouse_down(self, x: int, y: int, button: str = "left") -> None: ...
    def mouse_up(self, x: int, y: int, button: str = "left") -> None: ...
    def scroll(self, x: int, y: int, direction: str, amount: int) -> None: ...
    def type_text(self, text: str) -> None: ...
    def key(self, keys: list[str]) -> None: ...
    def hold_key(self, key: str, duration: float) -> None: ...
    def wait(self, seconds: float) -> None: ...
